### ISSUE TITLE
Question about validating 1.4.3 Contrast

### ISSUE THREAD

**Issue by Jinjiang** [pa11y/pa11y#341]
I'm not sure it should be asked here or in w3c org. But is that OK to use `text-shadow` with enough contract to `color`? For example pa11y will report an error for the code below:

```css
.card { color: white; background-color: white; text-shadow: 0 0 3px black; }
```

Thanks.
